### ISSUE TITLE
Extracting the hash from the database

### ISSUE THREAD

**Issue by polesapart** [HyP3r-/dbcrack#2]
From the docs: extract out of the database file the password hash and set DATA to that value

How do I do that?

**Comment by HyP3r-** [comment]
Hey. I'm really happy someone is interested in my open source projects. A friend of me asked me 2013 if I can help him with a DBISAM database where he lost the password. So please forgive me when I don't know each detail now correct. 

You should have the DBISAM Database Viewer where you can open the DAT-Files and explore the stored data. Use this Database Viewer to create a database table and set a password to this table (for example `test`). Now reproduce the encryption/hashing algorithm of the password so you know what hash you have to search.

I'm explaining you this way because I'm not sure if the hash is always at the exact same offset in the DAT-Files.

But in my case the hash is at offset `0xad` to `0xbc`. I'll update the documentation.
